# Generated by Django 4.2.7 on 2023-11-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_employee_created_at_employee_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile',
            field=models.ImageField(default='employees/employee_icon.png', null=True, upload_to='employees'),
        ),
    ]
